#!/bin/bash
#This script is used to tell the story/made up story of etc/passwd
while IFS=: read -r username password userid groupid userid_info home shell
do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userid_info"
done < /etc/passwd
