#!/usr/bin/env bash
#This is a script that prints Best School except on the 9th iteration, Hi is added
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
