#!/usr/bin/env bash
#This is a script that prints Best school until on 4th iteration and 8th iteration it prints bad luck and good luck respectively
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
